aruco_node:
  ros__parameters:
    # marker_size: 0.0575 # ID 21 Box
    marker_size: 0.1435 # ID 1 Patient
    aruco_dictionary_id: "DICT_5X5_250"
    image_topic: "/image"
    camera_info_topic: "/camera_info"
    camera_frame: "camera"
    filter_ids: [] # If list is empty, all IDs will be published
