aruco_node:
  ros__parameters:
    marker_size: 0.1435
    aruco_dictionary_id: "DICT_5X5_250"
    image_topic: "/image" # "/camera/color/image_raw"
    camera_info_topic:  "/stereo/left/camera_info" # "/camera/color/camera_info"
    camera_frame: "camera"
    filter_ids: [] # If list is empty, all IDs will be published
